server:
  port: 9090
spring:
  application:
    name: searchServer
  datasource:
    platform: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${dev_datasource.url}
    username: ${dev_datasource.username}
    password: ${dev_datasource.password}
  data:
    elasticsearch:
      cluster-name: elasticsearch
      cluster-nodes: 127.0.0.1:9300
  elasticsearch:
    rest:
      uris: ["http://127.0.0.1:9200"]

logging:
  level:
    com.netflix.discovery: 'info'
    org.springframework.boot: 'info'